#spring:
#  h2.console.enabled: true
#  datasource:
#    url: jdbc:h2:mem:boarddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate.ddl-auto: update
#    defer-datasource-initialization: true
#  server:
#    port: 8080
#--------------------------------------------------------------------------
#spring:
#
#  thymeleaf:
#    cache: false
#
#  jpa:
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope: openid, profile, email
#
#server:
#  port: ${PORT:8080}
#
#logging:
#  level:
#    org.thymeleaf: DEBUG
#--------------------------------------------------------------------------
# 공통
spring:
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

logging:
  level:
    org.thymeleaf: DEBUG

---
spring:
  profiles:
    active: local   # 기본 실행은 로컬


